### ISSUE TITLE
Oracle 11G : Compilation Error

### ISSUE THREAD

**Issue by xerocg** [antonscheffer/as_xlsx#7]
There was a compile error in the function read on Oracle 11G.
I fixed it now it compiles on Oracle 11G. (Error at line start with "       for r_n in ( "

Thank you for this package which helps me.

  function read
    ( p_xlsx          blob
    , p_sheets        varchar2 := null
    , p_cell          varchar2 := null
    , p_include_clobs varchar2 := null
    )
  return tp_all_cells pipelined
  is
    l_nr             number;
    l_cnt            pls_integer;
    l_cfh            tp_cfh;
    l_name           varchar2(32767);
    l_workbook       blob;
    l_workbook_rels  blob;
    l_shared_strings blob;
    l_file           blob;
    l_csid_utf8      integer := nls_charset_id( 'AL32UTF8' );
    type tp_strings     is table of varchar2(32767);
    type tp_string_lens is table of varchar2(32767);
    type tp_boolean_tab is table of boolean index by pls_integer;
    l_strings      tp_strings;
    l_string_lens  tp_string_lens;
    l_quote_prefix tp_boolean_tab;
    l_date_styles  tp_boolean_tab;
    l_time_styles  tp_boolean_tab;
    l_one_cell     tp_one_cell;
  begin
    l_cnt := get_count( p_xlsx );
    for i in 1 .. l_cnt
    loop
      exit when not get_central_file_header( p_xlsx, null, i, null, l_cfh );
      l_name := lower( utl_raw.cast_to_varchar2( l_cfh.name1 ) );
      if    l_name like '%workbook.xml'      then
        l_workbook      := parse_file( p_xlsx, l_cfh );
      elsif l_name like '%workbook.xml.rels' then
        l_workbook_rels := parse_file( p_xlsx, l_cfh );
      elsif l_name like '%sharedstrings.xml' then
        l_shared_strings := parse_file( p_xlsx, l_cfh );
        select xt1.txt
             , xt1.len
        bulk collect into l_strings, l_string_lens
        from xmltable( xmlnamespaces( default 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
                                    , 'http://purl.oclc.org/ooxml/spreadsheetml/main' as "x" )
                     , '( /sst/si, /x:sst/x:si )'
                       passing xmltype( xmldata => l_shared_strings, csid=> l_csid_utf8 )
                       columns txt varchar2(4000 char) path 'substring( string-join(.//*:t/text(), "" ), 1, 3999 )'
                             , len integer             path 'string-length( string-join(.//*:t/text(), "" ) )'
                     ) xt1;
      elsif l_name like '%styles.xml' then
        l_file := parse_file( p_xlsx, l_cfh );
       for r_n in ( 
SELECT xt2.xf_seq - 1 AS seq,
       xt2.xf_id AS num_fmt_id,
       xt2.xf_quoteprefix AS quote_prefix,
       LOWER(xt3.num_fmt_code) AS format
FROM xmltable(
         xmlnamespaces(
             DEFAULT 'http://schemas.openxmlformats.org/spreadsheetml/2006/main',
             'http://purl.oclc.org/ooxml/spreadsheetml/main' AS "x"
         ),
         '( /styleSheet, /x:styleSheet )'
         PASSING xmltype(
             xmldata => l_file,
             csid => nls_charset_id('AL32UTF8')
         )
         COLUMNS 
             cell_xfs XMLTYPE PATH '( cellXfs, x:cellXfs )',
             num_fmts XMLTYPE PATH '( numFmts, x:numFmts )'
     ) xt1
CROSS JOIN xmltable(
             '/*:cellXfs/*:xf'
             PASSING xt1.cell_xfs
             COLUMNS 
                 xf_seq FOR ORDINALITY,
                 xf_id INTEGER PATH '@numFmtId',
                 xf_quoteprefix VARCHAR2(4000) PATH '@quotePrefix'
         ) xt2
LEFT JOIN xmltable(
            '/*:numFmts/*:numFmt'
            PASSING xt1.num_fmts
            COLUMNS 
                num_fmt_id INTEGER PATH '@numFmtId',
                num_fmt_code VARCHAR2(4000) PATH '@formatCode'
        ) xt3
ON xt3.num_fmt_id = xt2.xf_id
                   )
        loop
          if    r_n.num_fmt_id between 14 and 17
             or instr( r_n.format, 'd' ) > 0
             or instr( r_n.format, 'y' ) > 0
          then
            l_date_styles( r_n.seq ) := null;
          elsif r_n.num_fmt_id between 18 and 22
             or r_n.num_fmt_id between 45 and 47
             or instr( r_n.format, 'h' ) > 0
             or instr( r_n.format, 'm' ) > 0
          then
            l_time_styles( r_n.seq ) := null;
          elsif r_n.quote_prefix in ( '1', 'true' )
          then
            l_quote_prefix( r_n.seq ) := null;
          end if;
        end loop;
        dbms_lob.freetemporary( l_file );
      end if;
    end loop;
    if l_workbook is null or l_workbook_rels is null
    then
      raise no_data_needed;
    end if;
    --
    for r_x in ( select xt1.d1904
                      , xt2.seq
                      , xt2.name
                      , xt3.target
                 from xmltable( xmlnamespaces( default 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
                                                     , 'http://purl.oclc.org/ooxml/spreadsheetml/main' as "x" )
                              , '( /workbook, /x:workbook )'
                                passing xmltype( xmldata => l_workbook, csid=> nls_charset_id( 'AL32UTF8' ) )
                                columns d1904  varchar2( 4000 ) path '*:workbookPr/@date1904'
                                      , sheets xmltype path '*:sheets'
                              ) xt1
                 cross join
                      xmltable( '*:sheets/*:sheet'
                                passing xt1.sheets
                                columns seq for ordinality
                                      , name    varchar2( 4000 ) path '@name'
                                      , sheetid varchar2( 4000 ) path '@sheetId'
                                      , rid     varchar2( 4000 ) path '@*:id[ namespace-uri(.) =
                                                                         ( "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
                                                                         , "http://purl.oclc.org/ooxml/officeDocument/relationships"
                                                                         ) ]'
                                      , state   varchar2( 4000 ) path '@state' ) xt2
                 join
                      xmltable( xmlnamespaces( default 'http://schemas.openxmlformats.org/package/2006/relationships' )
                              , '/Relationships/Relationship'
                                passing xmltype( xmldata => l_workbook_rels, csid=> nls_charset_id( 'AL32UTF8' ) )
                                columns type    varchar2( 4000 ) path '@Type'
                                      , target  varchar2( 4000 ) path '@Target'
                                      , id      varchar2( 4000 ) path '@Id' ) xt3
                 on xt3.id = xt2.rid
                 order by xt2.sheetid
               )
    loop
      if ( p_sheets is null
         or instr( ':' || p_sheets || ':', ':' || r_x.seq || ':' ) > 0
         or instr( ':' || p_sheets || ':', ':' || r_x.name || ':' ) > 0
         )
      then
        l_one_cell.sheet_nr   := r_x.seq;
        l_one_cell.sheet_name := r_x.name;
        l_one_cell.row_nr     := 0;
        for i in 1 .. l_cnt
        loop
          exit when not get_central_file_header( p_xlsx, null, i, null, l_cfh );
          if utl_raw.cast_to_varchar2( l_cfh.name1 ) like '%' || r_x.target
          then
            l_file := parse_file( p_xlsx, l_cfh );
            for r_c in ( select *
                         from xmltable( xmlnamespaces( default 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
                                                     , 'http://purl.oclc.org/ooxml/spreadsheetml/main' as "x" )
                                      , '( /worksheet/sheetData/row/c, /x:worksheet/x:sheetData/x:row/x:c )'
                                        passing xmltype( xmldata => l_file, csid=> l_csid_utf8 )
                                        columns v varchar2(4000) path '*:v'
                                              , f varchar2(4000) path '*:f'
                                              , t varchar2(4000) path '@t'
                                              , r varchar2(32)   path '@r'
                                              , s integer        path '@s'
                                              , rw integer       path './../@r'
                                              , txt varchar2(4000 char) path 'substring( string-join(.//*:t/text(), "" ), 1, 3999 )'
                                              , len integer             path 'string-length( string-join(.//*:t/text(), "" ) )'
                                      )
                       )
            loop
              if p_cell != r_c.r
              then
                continue;
              end if;
              if r_c.r is null
              then
                if l_one_cell.row_nr = r_c.rw
                then
                  l_one_cell.col_nr := l_one_cell.col_nr + 1;
                else
                  l_one_cell.col_nr := 1;
                end if;
              else
                l_one_cell.col_nr := col_alfan( r_c.r );
              end if;
              l_one_cell.row_nr     := coalesce( r_c.rw, l_one_cell.row_nr + 1 );
              l_one_cell.cell       := r_c.r;
              l_one_cell.formula    := r_c.f;
              l_one_cell.string_val := null;
              l_one_cell.number_val := null;
              l_one_cell.date_val   := null;
              l_one_cell.clob_val   := null;
              l_one_cell.string_len := null;
              if r_c.t = 's'
              then
                l_one_cell.cell_type := 'S';
                if r_c.v is not null
                then
                  l_one_cell.string_val := l_strings( to_number( r_c.v ) + 1 );
                  l_one_cell.string_len := l_string_lens( to_number( r_c.v ) + 1 );
                  if l_one_cell.string_len > 3999 and substr( p_include_clobs, 1, 1 ) in ( 'Y', 'y', '1' )
                  then
                    select xt1.txt
                    into l_one_cell.clob_val
                    from xmltable( '/*:sst/*:si[$i]'
                                   passing xmltype( xmldata => l_shared_strings, csid=> l_csid_utf8 )
                                         , to_number( r_c.v ) + 1 as "i"
                                   columns txt clob path 'string-join(.//*:t/text(), "" )'
                                 ) xt1;
                  end if;
                  if l_quote_prefix.exists( r_c.s )
                  then
                    l_one_cell.string_val := '''' || l_one_cell.string_val;
                    if l_one_cell.clob_val is not null
                    then
                      l_one_cell.clob_val := '''' || l_one_cell.clob_val;
                    end if;
                  end if;
                end if;
              elsif r_c.t = 'n' or r_c.t is null
              then
                l_nr := to_number( r_c.v
                                 , case when instr( upper( r_c.v ), 'E' ) = 0
                                     then translate( r_c.v, '.012345678,-+', 'D999999999' )
                                     else translate( substr( r_c.v, 1, instr( upper( r_c.v ) , 'E' ) - 1 ), '.012345678,-+', 'D999999999' ) || 'EEEE'
                                   end
                                 , 'NLS_NUMERIC_CHARACTERS=.,'
                                 );
                if l_date_styles.exists( r_c.s )
                then
                  l_one_cell.cell_type := 'D';
                  if lower( r_x.d1904 ) in ( 'true', '1' )
                  then
                    l_one_cell.date_val := date '1904-01-01' + l_nr;
                  else
                    l_one_cell.date_val := date '1900-03-01' + ( l_nr - 61 );
                  end if;
                elsif l_time_styles.exists( r_c.s )
                then
                  l_one_cell.cell_type := 'S';
                  l_one_cell.string_val := to_char( numtodsinterval(  l_nr, 'day' ) );
                  l_one_cell.string_len := length( l_one_cell.string_val );
                else
                  l_one_cell.cell_type := 'N';
                  l_nr := round( l_nr, 14 - substr( to_char( l_nr, 'TME' ), -3 ) );
                  l_one_cell.number_val := l_nr;
                end if;
              elsif r_c.t = 'd'
              then
                l_one_cell.cell_type := 'D';
                l_one_cell.date_val := cast( to_timestamp_tz( r_c.v, 'yyyy-mm-dd"T"hh24:mi:ss.ffTZH:TZM' ) as date );
              elsif r_c.t = 'inlineStr'
              then
                l_one_cell.cell_type := 'S';
                l_one_cell.string_val := r_c.txt;
                l_one_cell.string_len := r_c.len;
                if     l_one_cell.string_len > 3999
                   and substr( p_include_clobs, 1, 1 ) in ( 'Y', 'y', '1' )
                   and r_c.r is not null
                then
                  select xt1.txt
                  into l_one_cell.clob_val
                  from xmltable( '/*:worksheet/*:sheetData/*:row/*:c[@r=$r]'
                                 passing xmltype( xmldata => l_file, csid=> l_csid_utf8 )
                                       , r_c.r as "r"
                                 columns txt clob path 'string-join(.//*:t/text(), "" )'
                               ) xt1;
                end if;
              elsif r_c.t in ( 'str', 'e' )
              then
                l_one_cell.cell_type := 'S';
                l_one_cell.string_val := r_c.v;
                l_one_cell.string_len := length( l_one_cell.string_val );
              elsif r_c.t = 'b'
              then
                l_one_cell.cell_type := 'S';
                l_one_cell.string_val := case r_c.v
                                           when '1' then 'TRUE'
                                           when '0' then 'FALSE'
                                           else r_c.v
                                        end;
                l_one_cell.string_len := length( l_one_cell.string_val );
              end if;
              pipe row( l_one_cell );
            end loop;
            dbms_lob.freetemporary( l_file );
            exit;
          end if;
        end loop;
      end if;
    end loop;
    --
    dbms_lob.freetemporary( l_workbook );
    dbms_lob.freetemporary( l_workbook_rels );
    if l_strings is not null
    then
      l_strings.delete;
      l_string_lens.delete;
      dbms_lob.freetemporary( l_shared_strings );
    end if;
    l_date_styles.delete;
    l_time_styles.delete;
    l_quote_prefix.delete;
    raise no_data_needed;
  end read;
  --

**Comment by antonscheffer** [comment]
Strange, it compiles on my 11G, 11.2.0.2.0.
As far as I can see you only renamed some columns and removed some XML-wildcards in xt2 and xt3 and that solved your compilation problem?

**Comment by xerocg** [comment]
My version of 11G is 11.2.0.1.0.

Reading .xlsm file does not work. I went back to an old version which works. I didn't take the time to do much debugging.

**Comment by antonscheffer** [comment]
Might be the removal of the those wildcards :) It is a functional change.

**Comment by antonscheffer** [comment]
So, I finally got a 11.2.0.1 database. I can reproduce (and fix) the compilation error. But 11.2 in general, and 11.2.0.1 specifically, has so many bugs that I'm not able to get as_xlsx.read working with XMLTable. So sorry, as_xlsx is not suitable for 11.2.0.1.
